name: stroke
services:
  postgres:
    image: postgres:16-alpine
    container_name: sft-db
    ports:
      - 5432:5432 
    volumes:
      - sft-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - sft-net

  backend:
    container_name: sft-backend
    image: duxmazter/stroke-backend:latest
    ports:
      - 3000:3000  
    networks:
      - sft-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432  
      - POSTGRES_HOST=sft-db
      - POSTGRES_USER=${POSTGRES_USER}        
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}

  frontend:
    container_name: sft-frontend
    image: duxmazter/stroke-frontend:latest
    ports:
      - 80:80
    networks:
      - sft-net
    environment:
      - VITE_APP_API_URL=http://sft-backend:3000 

volumes:
  sft-data:

networks:
  sft-net: